author: Paulius Gudonis
author_url: https://pgu.dev
github_url: https://github.com/nakkht/quick-constraint
module: QuickConstraint
output: docs
theme: apple
swift_build_tool: spm
build_tool_arguments: [-Xswiftc, -swift-version, -Xswiftc, "5"]
module_version: 0.9.0
clean: true
min_acl: internal