author: Paulius Gudonis
author_url: https://pgu.dev
github_url: https://github.com/nakkht/quick-constraint
module: QuickConstraint
output: docs
theme: apple
swift_build_tool: xcodebuild
build_tool_arguments: [-scheme, "QuickConstraint", -sdk, "iphoneos"]
module_version: 0.9.0
clean: true
min_acl: internal