os: osx
language: swift

branches:
  only:
  - master
  - develop

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=QuickConstraint.xcodeproj
    - SCHEME=QuickConstraint

jobs:
  include:
    - osx_image: xcode11.6
      env: DESTINATION='platform=iOS Simulator,name=iPhone 11 Pro,OS=latest'
    - osx_image: xcode11.6
      env: DESTINATION='platform=iOS Simulator,name=iPhone 5s,OS=12.4'
    - osx_image: xcode11.6
      env: DESTINATION='platform=iOS Simulator,name=iPhone 5s,OS=11.4'
    - osx_image: xcode11.6
      env: DESTINATION='platform=iOS Simulator,name=iPhone 5s,OS=10.3.1'
    - osx_image: xcode10.2
      env: DESTINATION='platform=iOS Simulator,name=iPhone 5s,OS=9.0'

    - osx_image: xcode11.6
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=latest'
    - osx_image: xcode11.6
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=12.4'
    - osx_image: xcode11.6
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=11.4'
    - osx_image: xcode11.6
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=10.2'
    - osx_image: xcode10.2
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=9.0'

    - osx_image: xcode11.6
      env: DESTINATION='platform=OS X,arch=x86_64'
    - osx_image: xcode11.3
      env: DESTINATION='platform=OS X,arch=x86_64'

    - osx_image: xcode12
      env: DESTINATION='platform=iOS Simulator,name=iPhone 11,OS=latest'
    - osx_image: xcode12
      env: DESTINATION='platform=tvOS Simulator,name=Apple TV,OS=latest'
    - osx_image: xcode12
      env: DESTINATION='platform=OS X,arch=x86_64'

  allow_failures:
    osx_image: xcode12

script:
  - xcodebuild build -project $PROJECT -scheme $SCHEME -destination "${DESTINATION}"